In [2]:
import pandas as pd
df = pd.read_csv('CADASTRO_IES_2020.CSV', encoding='ISO-8859-1', sep=';', low_memory=False)

df.head()

,NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,...,DOC_EX_60_MAIS,DOC_EX_BRANCA,DOC_EX_PRETA,DOC_EX_PARDA,DOC_EX_AMARELA,DOC_EX_INDÍGENA,DOC_EX_COR_ND,DOC_EX_BRA,DOC_EX_EST,DOC_EX_COM_DEFICIÊNCIA
0,2020,Norte,1,Rondônia,RO,11,Ariquemes,1100023,0,Leste Rondoniense,...,2,18,1,8,0,0,27,54,0,0
1,2020,Norte,1,Rondônia,RO,11,Ariquemes,1100023,0,Leste Rondoniense,...,3,45,5,17,2,0,0,67,2,0
2,2020,Norte,1,Rondônia,RO,11,Cacoal,1100049,0,Leste Rondoniense,...,9,114,2,31,2,0,3,152,0,0
3,2020,Norte,1,Rondônia,RO,11,Cacoal,1100049,0,Leste Rondoniense,...,1,30,1,4,0,0,4,39,0,0
4,2020,Norte,1,Rondônia,RO,11,Cacoal,1100049,0,Leste Rondoniense,...,0,14,0,7,0,0,18,39,0,0

In [9]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2457 entries, 0 to 2456
Data columns (total 81 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   NU_ANO_CENSO                    2457 non-null   int64
 1   NO_REGIAO_IES                   2457 non-null   object
 2   CO_REGIAO_IES                   2457 non-null   int64
 3   NO_UF_IES                       2457 non-null   object
 4   SG_UF_IES                       2457 non-null   object
 5   CO_UF_IES                       2457 non-null   int64
 6   NO_MUNICIPIO_IES                2457 non-null   object
 7   CO_MUNICIPIO_IES                2457 non-null   int64
 8   IN_CAPITAL_IES                  2457 non-null   int64
 9   NO_MESORREGIAO_IES              2457 non-null   object
 10  CO_MESORREGIAO_IES              2457 non-null   int64
 11  NO_MICRORREGIAO_IES             2457 non-null   object
 12  CO_MICRORREGIAO_IES             2457 non-null   int64
 13  TP_ORGANIZACAO_ACADEMICA        2457 non-null   int64
 14  TP_CATEGORIA_ADMINISTRATIVA     2457 non-null   int64
 15  NO_MANTENEDORA                  2457 non-null   object
 16  CO_MANTENEDORA                  2457 non-null   int64
 17  NO_IES                          2457 non-null   object
 18  SG_IES                          2046 non-null   object
 19  CO_IES                          2457 non-null   int64
 20  DS_ENDERECO_IES                 2457 non-null   object
 21  DS_NUMERO_ENDERECO_IES          2456 non-null   object
 22  DS_COMPLEMENTO_ENDERECO_IES     2456 non-null   object
 23  NO_BAIRRO_IES                   2457 non-null   object
 24  NU_CEP_IES                      2413 non-null   float64
 25  QT_TEC_TOTAL                    2457 non-null   int64
 26  QT_TEC_FUNDAMENTAL_INCOMP_FEM   2457 non-null   int64
 27  QT_TEC_FUNDAMENTAL_INCOMP_MASC  2457 non-null   int64
 28  QT_TEC_FUNDAMENTAL_COMP_FEM     2457 non-null   int64
 29  QT_TEC_FUNDAMENTAL_COMP_MASC    2457 non-null   int64
 30  QT_TEC_MEDIO_FEM                2457 non-null   int64
 31  QT_TEC_MEDIO_MASC               2457 non-null   int64
 32  QT_TEC_SUPERIOR_FEM             2457 non-null   int64
 33  QT_TEC_SUPERIOR_MASC            2457 non-null   int64
 34  QT_TEC_ESPECIALIZACAO_FEM       2457 non-null   int64
 35  QT_TEC_ESPECIALIZACAO_MASC      2457 non-null   int64
 36  QT_TEC_MESTRADO_FEM             2457 non-null   int64
 37  QT_TEC_MESTRADO_MASC            2457 non-null   int64
 38  QT_TEC_DOUTORADO_FEM            2457 non-null   int64
 39  QT_TEC_DOUTORADO_MASC           2457 non-null   int64
 40  IN_ACESSO_PORTAL_CAPES          2457 non-null   int64
 41  IN_ACESSO_OUTRAS_BASES          2457 non-null   int64
 42  IN_ASSINA_OUTRA_BASE            2457 non-null   int64
 43  IN_REPOSITORIO_INSTITUCIONAL    2457 non-null   int64
 44  IN_BUSCA_INTEGRADA              2457 non-null   int64
 45  IN_SERVICO_INTERNET             2457 non-null   int64
 46  IN_PARTICIPA_REDE_SOCIAL        2457 non-null   int64
 47  IN_CATALOGO_ONLINE              2457 non-null   int64
 48  QT_PERIODICO_ELETRONICO         2457 non-null   int64
 49  QT_LIVRO_ELETRONICO             2457 non-null   int64
 50  QT_DOCENTE_TOTAL                2457 non-null   int64
 51  QT_DOCENTE_EXE                  2457 non-null   int64
 52  DOC_EX_FEMI                     2457 non-null   int64
 53  DOC_EX_MASC                     2457 non-null   int64
 54  DOC_EX_SEM_GRAD                 2457 non-null   int64
 55  DOC_EX_GRAD                     2457 non-null   int64
 56  DOC_EX_ESP                      2457 non-null   int64
 57  DOC_EX_MEST                     2457 non-null   int64
 58  DOC_EX_DOUT                     2457 non-null   int64
 59  DOC_EX_INT                      2457 non-null   int64
 60  DOC_EX_INT_DE                   2457 non-null   int64
 61  DOC_EX_INT_SEM_DE               2457 non-null   int64
 62  DOC_EX_PARC                     2457 non-null   int64
 63  DOC_EX_HOR                      2457 non-null   int64
 64  DOC_EX_0_29                     2457 non-null   int64
 65  DOC_EX_30_34                    2457 non-null   int64
 66  DOC_EX_35_39                    2457 non-null   int64
 67  DOC_EX_40_44                    2457 non-null   int64
 68  DOC_EX_45_49                    2457 non-null   int64
 69  DOC_EX_50_54                    2457 non-null   int64
 70  DOC_EX_55_59                    2457 non-null   int64
 71  DOC_EX_60_MAIS                  2457 non-null   int64
 72  DOC_EX_BRANCA                   2457 non-null   int64
 73  DOC_EX_PRETA                    2457 non-null   int64
 74  DOC_EX_PARDA                    2457 non-null   int64
 75  DOC_EX_AMARELA                  2457 non-null   int64
 76  DOC_EX_INDÍGENA                 2457 non-null   int64
 77  DOC_EX_COR_ND                   2457 non-null   int64
 78  DOC_EX_BRA                      2457 non-null   int64
 79  DOC_EX_EST                      2457 non-null   int64
 80  DOC_EX_COM_DEFICIÊNCIA          2457 non-null   int64
dtypes: float64(1), int64(67), object(13)
memory usage: 1.5+ MB
None

In [17]:
# Análise exploratória
print("Análise exploratória:")
print("Total de linhas:", len(df))
print("\nResumo estatístico:")
print(df.describe())
print("\nQuantidade de valores NaN por coluna:")
print(df.isna().sum())

Análise exploratória:
Total de linhas: 2457

Resumo estatístico:
       NU_ANO_CENSO  CO_REGIAO_IES    CO_UF_IES  CO_MUNICIPIO_IES  \
count        2457.0    2457.000000  2457.000000      2.457000e+03
mean         2020.0       2.994709    33.476190      3.365560e+06
std             0.0       1.052941     9.622577      9.629679e+05
min          2020.0       1.000000    11.000000      1.100023e+06
25%          2020.0       2.000000    29.000000      2.909208e+06
50%          2020.0       3.000000    33.000000      3.306305e+06
75%          2020.0       4.000000    41.000000      4.106407e+06
max          2020.0       5.000000    53.000000      5.300108e+06

       IN_CAPITAL_IES  CO_MESORREGIAO_IES  CO_MICRORREGIAO_IES  \
count     2457.000000         2457.000000          2457.000000
mean         0.348392            5.836793            23.398860
std          0.476558            4.304170            18.938151
min          0.000000            1.000000             1.000000
25%          0.000000            3.000000             9.000000
50%          0.000000            5.000000            18.000000
75%          1.000000            7.000000            32.000000
max          1.000000           15.000000            66.000000

       TP_ORGANIZACAO_ACADEMICA  TP_CATEGORIA_ADMINISTRATIVA  CO_MANTENEDORA  \
count               2457.000000                  2457.000000     2457.000000
mean                   2.720798                     4.117623     6170.891738
std                    0.634406                     1.039725     7016.440056
min                    1.000000                     1.000000        1.000000
25%                    3.000000                     4.000000      611.000000
50%                    3.000000                     4.000000     1827.000000
75%                    3.000000                     5.000000    15514.000000
max                    5.000000                     7.000000    18035.000000

       ...  DOC_EX_60_MAIS  DOC_EX_BRANCA  DOC_EX_PRETA  DOC_EX_PARDA  \
count  ...     2457.000000    2457.000000   2457.000000   2457.000000
mean   ...       17.485958      81.145299      3.253561     22.127391
std    ...       68.097015     228.373504     10.386603     59.115140
min    ...        0.000000       0.000000      0.000000      0.000000
25%    ...        1.000000      10.000000      0.000000      2.000000
50%    ...        3.000000      22.000000      1.000000      6.000000
75%    ...       11.000000      61.000000      2.000000     16.000000
max    ...     1766.000000    5352.000000    217.000000    821.000000

       DOC_EX_AMARELA  DOC_EX_INDÍGENA  DOC_EX_COR_ND   DOC_EX_BRA  \
count     2457.000000      2457.000000    2457.000000  2457.000000
mean         1.531543         0.188848      40.833130   147.291819
std          6.697446         0.802169     192.527698   363.420377
min          0.000000         0.000000       0.000000     0.000000
25%          0.000000         0.000000       1.000000    19.000000
50%          0.000000         0.000000       3.000000    42.000000
75%          1.000000         0.000000      14.000000   113.000000
max        160.000000        13.000000    3221.000000  5623.000000

        DOC_EX_EST  DOC_EX_COM_DEFICIÊNCIA
count  2457.000000             2457.000000
mean      1.787953                0.593000
std      10.738347                2.561857
min       0.000000                0.000000
25%       0.000000                0.000000
50%       0.000000                0.000000
75%       1.000000                0.000000
max     283.000000               71.000000

[8 rows x 68 columns]

Quantidade de valores NaN por coluna:
NU_ANO_CENSO              0
NO_REGIAO_IES             0
CO_REGIAO_IES             0
NO_UF_IES                 0
SG_UF_IES                 0
                         ..
DOC_EX_INDÍGENA           0
DOC_EX_COR_ND             0
DOC_EX_BRA                0
DOC_EX_EST                0
DOC_EX_COM_DEFICIÊNCIA    0
Length: 81, dtype: int64

In [22]:
# Remover linhas com valores nulos

df.dropna(inplace=True)

In [ ]:
# Criar um gráfico de barras para contagem de alunos por estado
state_counts = df['NO_UF_IES'].value_counts()
state_counts.plot(kind='bar', title='Contagem de Alunos por Estado', figsize=(10, 6))
plt.xlabel('Estado')
plt.ylabel('Contagem de Alunos')
plt.show()